export const cacheTags = {
  users: "users:list",
  roles: "roles:list",
  permissions: "permissions:list",
  rolePerms: (roleId: string) => `role-perms:${roleId}`,
  clients: "clients:list", 
  costing: "costing:params",
  quotes: "quotes:list",
  inventoryProducts: "inventory:products",
  inventoryMovs: "inventory:movs",
  inventoryKardex: (sku: string) => `inventory:kardex:${sku}`,
  purchasesSC: "purchases:sc",
  purchasesOC: "purchases:oc",
  providers: "purchases:providers",
};
